config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users, only: [:index, :show]
  resources :users do
    resources :cvs
  end
  resources :agents
  resources :jobs

  match '/about', to: 'static_pages#about', via: :get
  match '/faq', to: 'static_pages#faq', via: :get

  root to: "jobs#index"

  post 'user_jobs/add'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  open        :boolean
#  closed_date :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  summary     :text
#  agent_id    :integer
#  user_id     :integer
#

class Job < ApplicationRecord
  belongs_to :agent
  has_many :user_jobs
  has_many :users, through: :user_jobs

  validates :title, length: { in: 1..50 }, presence: true
  validates :summary, length: { in: 1..250 }, presence: true
  validates :body, length: { in: 1..7500 }, presence: true
  validates :agent_id, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  before_action :get_agents, only: %i[new create edit update]
  before_action :set_page_title, only: %i[new show index edit]
  before_action :set_partial_to_render, only: %i[new edit]
  before_action :get_user, only: %i[new create edit update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.order('created_at DESC')
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show; end

  # GET /jobs/new
  def new
    @job = @user.jobs.build
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = @user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  def set_page_title
    @page_title = case action_name
      when 'index'
        if Job.count < 1
          'We Do Not Have Any Jobs Available. Please Check Back Soon.'
        else
          'We Need People to Fill These Jobs'
        end
      when 'show'
        @job.title
      when 'edit'
        'Make Changes to This Job Post'
      when 'new'
        'Create a New Job Post'
      else
        ''
    end
  end

  def set_partial_to_render
    @partial_to_render = 'form'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:title, :body, :open, :closed_date, :summary, :agent_id)
  end

  def get_agents
    @agent_list = Agent.all
  end

  def get_user
    @user = current_user
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for @job do |f|
  = f.error_notification
  = render 'shared/error_messages', object: f.object
  .form-inputs
    = f.input :title, label: 'Job Title', autofocus: true, hint: raw("Give a short and clear title for this position.<br>Example: \"Housekeeping in Casino\"")
    %hr
    = f.input :summary, label: 'Job Summary', input_html: { rows: 2 }, hint: raw("Write a short summary of the position. Just one or two lines.<br>Example: \"Seeking males or females for basic cleaning duties in a hotel / casino. Must speak Cantonese.\"")
    %hr
    = f.input :body, label: 'Job Description', input_html: { rows: 10 }, hint: 'Give a full, detailed description of the job and all of the requirements the woker needs to have.'
    %hr
    = f.input :open,
      as: :radio_buttons,
      label: 'Is this job open?',
      collection: [['Open', true], ['Closed', false]],
      checked: true,
      item_wrapper_class: 'radio-inline',
      hint: raw("If the job is marked \"Open\" it will be visible to everyone on the main page.<br>If the job is marked \"Closed\" it will only be visible to you.")
    %hr
    = f.input :agent_id, label: 'Which Agent is this Job for?', collection: @agent_list, input_html: { style: 'width: 300px;' }
  .form-actions
    = f.button :submit, 'Save Job', class: 'btn-primary'

app/views/jobs/edit.html.haml
= render 'shared/display_panel'

app/views/jobs/index.html.haml
.row
  .col-sm-10.col-sm-offset-1
    - if @page_title
      %h2
        = @page_title
    - @jobs.each do |job|
      -if job.open
        .panel.panel-primary
          .panel-heading
            %h4.job-title
              = link_to job.title, job
              = link_to "View Job", job, class: 'btn btn-success pull-right'
          .panel-body
            %p= job.summary

app/views/jobs/new.html.haml
= render 'shared/display_panel', partial_to_render: 'form'

app/views/jobs/show.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.text-center
        - if @page_title
          %h2
            = @page_title
      .panel-body
        = simple_format(@job.body)
      .panel-footer.text-light.clearfix
        - if current_user.admin
          %p
            = link_to 'Edit', edit_job_path(@job), class: 'btn btn-success'
        - else
          %p
            - if @job.open
              %h4
                We are looking for people to fill this position!
                = button_to 'Apply', user_jobs_add_path, class: 'btn btn-success pull-right'
            - else
              %h4 We're sorry, but this job has already been filled.