config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users, only: [:index, :show]
  resources :users do
    resources :cvs
  end
  resources :agents
  resources :jobs

  match '/about', to: 'static_pages#about', via: :get
  match '/faq', to: 'static_pages#faq', via: :get

  root to: "jobs#index"

  post 'user_jobs/add'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/agent.rb
# == Schema Information
#
# Table name: agents
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  address    :text
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Agent < ApplicationRecord
  has_many :jobs

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email, with: /(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/, multiline: true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: %i[show edit update destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1
  # GET /agents/1.json
  def show; end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit; end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agent
    @agent = Agent.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def agent_params
    params.require(:agent).permit(:name, :email, :address, :phone)
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_form.html.haml
= simple_form_for @agent do |f|
  = f.error_notification
  = render 'shared/error_messages', object: f.object
  .form-inputs
    = f.input :name, label: 'Agent\'s Name'
    = f.input :email, label: 'Agent\'s Email Address'
    = f.input :address, label: 'Agent\'s Address', input_html: { value: 'None' }
    = f.input :phone, label: 'Agent\'s Phone Number'

  .form-actions
    = f.button :submit, 'Save Agent', class: 'btn-primary'

app/views/agents/edit.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.text-center
        %h2 Make Changes to the Agent Profile
      .panel-body
        = render 'form'

app/views/agents/index.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.agent-title
        .row
          .col-sm-6
            %h3 Available Agents
          .col-sm-6
            = link_to "Create a New Agent", new_agent_path, class: 'btn btn-success pull-right-lg'
      .panel-body
        - @agents.each do |agent|
          %h4
            = link_to agent.name, agent, class: 'agent-name'
          .row
            .col-sm-6
              %b Phone:
              = agent.phone
            .col-sm-6
              %b Email:
              = agent.email
          %hr

app/views/agents/new.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.text-center
        %h2 Add a New Agent Profile
      .panel-body
        = render 'form'

app/views/agents/show.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading
        %h3= @agent.name
      .panel-body
        %h4
          %b Email:
        %p
          = @agent.email
        %hr
        %h4 
          %b Address:
        %p
          = simple_format(@agent.address)
        %hr
        %h4
          %b Phone:
        %p
          = @agent.phone