config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users, only: [:index, :show]
  resources :users do
    resources :cvs
  end
  resources :agents
  resources :jobs

  match '/about', to: 'static_pages#about', via: :get
  match '/faq', to: 'static_pages#faq', via: :get

  root to: "jobs#index"

  post 'user_jobs/add'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/cv.rb
# == Schema Information
#
# Table name: cvs
#
#  id                       :integer          not null, primary key
#  user_id                  :integer
#  first_name               :string
#  middle_name              :string
#  last_name                :string
#  age                      :integer
#  height                   :integer
#  weight                   :integer
#  marital_status           :string
#  children                 :integer
#  phone_number             :string
#  current_city             :string
#  current_country          :string
#  skills                   :text
#  work_visa                :boolean
#  visa_exp_date            :date
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  passport_country         :string
#  passport_number          :string
#  passport_expiration_date :date
#  head_pic_file_name       :string
#  head_pic_content_type    :string
#  head_pic_file_size       :integer
#  head_pic_updated_at      :datetime
#  body_pic_file_name       :string
#  body_pic_content_type    :string
#  body_pic_file_size       :integer
#  body_pic_updated_at      :datetime
#  current_address          :string
#  visa_country             :string
#  completed                :boolean
#

class Cv < ApplicationRecord
  belongs_to :user
  
  has_many :educations, dependent: :destroy
  has_many :languages, dependent: :destroy
  has_many :previous_employments, dependent: :destroy
  accepts_nested_attributes_for :educations, allow_destroy: true
  accepts_nested_attributes_for :languages, allow_destroy: true
  accepts_nested_attributes_for :previous_employments, allow_destroy: true
  
  after_initialize :init
  before_save :is_complete?
  
  has_attached_file :head_pic, styles: { thumb: '100x100', small: '300x300', large: '600x600' }
  validates_attachment_content_type :head_pic, content_type: /\Aimage\/.*\z/
  has_attached_file :body_pic, styles: { thumb: '100x100', small: '300x300', large: '600x600' }
  validates_attachment_content_type :body_pic, content_type: /\Aimage\/.*\z/

  validates :first_name, length: { in: 1..30 }, allow_blank: true
  validates :middle_name, length: { in: 1..30 }, allow_blank: true
  validates :last_name, length: { in: 1..30 }, allow_blank: true
  validates :age, numericality: { only_integer: true }, allow_blank: true
  validates :height, numericality: { only_integer: true }, allow_blank: true
  validates :weight, numericality: { only_integer: true }, allow_blank: true
  validates :marital_status, inclusion: { in: %w[Single Married Separated Divorced Widowed] }
  validates :children, numericality: { only_integer: true }, allow_blank: true
  validates :phone_number, length: { in: 7..25 }, allow_blank: true
  validates :current_address, length: { maximum: 255 }, allow_blank: true
  validates :current_city, length: { maximum: 50 }, allow_blank: true
  validates :current_country, length: { maximum: 50 }, allow_blank: true
  validates :skills, length: { maximum: 250 }, allow_blank: true
  validates :work_visa, inclusion: { in: [true, false] }
  validates :visa_exp_date, timeliness: { on_or_after: -> { Date.current } }, allow_blank: true
  validates :passport_country, length: { maximum: 50 }, allow_blank: true
  validates :passport_number, length: { in: 5..25 }, allow_blank: true
  validates :passport_expiration_date, timeliness: { on_or_after: -> { Date.current } }, allow_blank: true


  def init
    self.completed = false if self.completed.nil?
  end

  def is_complete?
    self.completed = true
    self.attributes.each do |atr|
      self.completed = false if atr.blank?
      return if !self.completed
    end
    self.educations.each do |edu|
      edu.attributes.each do |ea|
        self.completed = false if edu.blank?
        return if !self.completed
      end
    end
    self.languages.each do |exp|
      exp.attributes.each do |exa|
        self.completed = false if exa.blank?
        return if !self.completed
      end
    end
    true
  end

  # Set the list of preferred countries.
  PREFERRED_COUNTRIES = %w[Indonesia
                    Philippines
                    Malaysia
                    Thailand
                    India
                    Nepal
                    Singapore
                    Bangladesh
                    Cambodia
                    China
                    French\ Polynesia
                    Hong\ Kong
                    Macao
                    Micronesia
                    Sri\ Lanka
                    Taiwan
                    Viet\ Nam]
 

end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  # before_action :set_user
  # before_action :set_cv
  before_action :set_language_levels, only: %i[new edit]

  # GET /cvs
  # GET /cvs.json
  def index
    @cvs = Cv.all
  end

  # GET /cvs/1
  # GET /cvs/1.json
  def show
    @cv = current_user.cv
  end

  # GET /cvs/new
  def new
    @cv = current_user.build_cv
    @cv.languages.build(name: 'English', read: 'None', write: 'None', speak: 'None', listen: 'None')
    @cv.languages.build(name: 'Cantonese', read: 'None', write: 'None', speak: 'None', listen: 'None')
    @cv.languages.build(name: 'Mandarin', read: 'None', write: 'None', speak: 'None', listen: 'None')
    @cv.educations.build
    @cv.previous_employments.build
  end

  # GET /cvs/1/edit
  def edit
  end

  # POST /cvs
  # POST /cvs.json
  def create
    @cv = current_user.create_cv(cv_params)
    respond_to do |format|
      if @cv.save
        format.html { redirect_to user_cv_url(current_user, @cv), notice: 'Cv was successfully created.' }
        format.json { render :show, status: :created, location: @cv }
      else
        format.html { render :new }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cvs/1
  # PATCH/PUT /cvs/1.json
  def update
    respond_to do |format|
      @cv = current_user.cv
      if @cv.update(cv_params)
        format.html { redirect_to user_cv_path, notice: 'Cv was successfully updated.' }
        format.json { render :show, status: :ok, location: @cv }
      else
        format.html { render :edit }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.json
  def destroy
    @cv.destroy
    respond_to do |format|
      format.html { redirect_to cvs_url, notice: 'Cv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cv
    @cv = current_user.cv
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cv_params
    params.require(:cv).permit(
      :first_name,
      :middle_name,
      :last_name,
      :age,
      :height,
      :weight,
      :marital_status,
      :children,
      :phone_number,
      :current_city,
      :current_country,
      :skills,
      :work_visa,
      :visa_exp_date,
      :visa_country,
      :passport_country,
      :passport_number,
      :passport_expiration_date,
      :head_pic,
      :body_pic,
      :current_address,
      :completed,
      languages_attributes: [:id,
        :name,
        :read,
        :write,
        :speak,
        :listen,
        :_destroy],
      educations_attributes: [:id,
        :name,
        :city,
        :country,
        :years_attended,
        :year_completed,  
        :months_attended,
        :graduated,
        :_destroy],
      previous_employments_attributes: [:id,
        :employer_name,
        :job_duties,
        :months,
        :years,
        :ended_year, 
        :location,
        :_destroy])
      
  end

  def set_user
    @user = current_user if user_signed_in?
  end

  def set_language_levels
    @language_levels = %w(None Poor Good Perfect)
  end

  def set_end_years
    @end_years = 111
  end

end

app/helpers/cvs_helper.rb
module CvsHelper
  def is_complete?
    self.cv.attributes.each do |atr|
      return false if atr.blank?
    end
    self.cv.educations.each do |edu|
      edu.attributes.each do |ea|
        return false if ea.blank?
      end
    end
    self.cv.languages.each do |exp|
      exp.attributes.each do |exa|
        return false if exa.blank?
      end
    end
    true
  end
end

app/views/cvs/_education_fields.html.haml
.nested-fields
  .form-group
    = f.input :name, label: 'School Name', wrapper_html: { class: 'col-sm-12' }
    = f.input :city, wrapper_html: { class: 'col-sm-6' }
    = f.input :country, priority: Cv::PREFERRED_COUNTRIES, selected: 'ID', wrapper_html: { class: 'col-sm-6' }
    -# %br
    -# %br
  .form-group
    %strong.col-sm-3 How long did you attend:
    = f.input :years_attended, label: 'Years', collection: 0..20, selected: 0, input_html: { style: 'width: 80px' }, wrapper_html: { class: 'col-sm-2' }
    = f.input :months_attended, label: 'Months', collection: 0..12, selected: 0, input_html: { style: 'width: 80px' }, wrapper_html: { class: 'col-sm-2' }
    = f.input :year_completed, label: 'Year Completed', collection: 1950..2018, wrapper_html: { class: 'col-sm-4' }
  .form-group
    = f.input :graduated, as: :radio_buttons, label: "Did you graduate?", item_wrapper_class: 'radio-inline', collection: [['Yes', true], ['No', false]], wrapper_html: { class: 'col-sm-12' }
  .links.clearfix
    = link_to_remove_association "Remove Education", f, class: 'btn btn-danger btn-sm pull-right'
  %hr

app/views/cvs/_form.html.haml
.container-fluid
  = simple_form_for [current_user, current_user.cv], html: {multipart: true} do |f|
    = f.error_notification
    = render 'shared/error_messages', object: f.object
    .form-inputs
      %fieldset
        %legend
          Name
        .form-group
          = f.input :first_name, label: 'First', wrapper_html: { class: 'col-sm-4' }
          = f.input :middle_name, label: 'Middle', wrapper_html: { class: 'col-sm-4' }
          = f.input :last_name, label: 'Last', wrapper_html: { class: 'col-sm-4' }
      %fieldset
        %legend
          Personal Information
        .form-group
          = f.input :age, collection: 10..100, selected: 21, wrapper_html: { class: 'col-md-2 col-sm-4' }
          = f.input :height, collection: 120..220, selected: 165, wrapper_html: { class: 'col-md-2 col-sm-4' }
          = f.input :weight, collection: 30..130, selected: 60, wrapper_html: { class: 'col-md-2 col-sm-4' }
          = f.input :marital_status, collection: ['Single', 'Married', 'Separated', 'Divorced', 'Widowed'], selected: 'Single', wrapper_html: { class: 'col-md-3 col-sm-6' }
          = f.input :children, collection: 0..15, selected: 0, wrapper_html: { class: 'col-md-3 col-sm-6' }
      %fieldset
        %legend
          Local Address and Phone Number
        .form-group
          = f.input :current_address, as: :text, label: 'Street Address', input_html: { rows: 3 }, wrapper_html: { class: 'col-sm-12' }
          = f.input :current_city, label: 'City', input_html: { value: 'Macau' }, wrapper_html: { class: 'col-sm-4' }
          = f.input :current_country, priority: Cv::PREFERRED_COUNTRIES, selected: "MO", wrapper_html: { class: 'col-sm-4' }
          = f.input :phone_number, wrapper_html: { class: 'col-sm-4' }
      %fieldset
        %legend
          Languages
        %strong Please indicate known languages and ability level in each:
        %br
        %br
        #languages
          = f.simple_fields_for :languages do |language|
            = render 'language_fields', f:language
          .links
            = link_to_add_association 'Add Language', f, :languages, class: 'btn btn-success btn-sm'
      %fieldset
        %legend
          Education
        %strong Please give any education and indicate where and how long you attended:
        %br
        %br
        #educations
          = f.simple_fields_for :educations do |education|
            = render 'education_fields', f: education
          .links
            = link_to_add_association 'Add Education', f, :educations, class: 'btn btn-success btn-sm'
      %fieldset
        %legend
          Previous Jobs
        %strong What jobs have you done before:
        %br
        %br
        #previous_employments
          = f.simple_fields_for :previous_employments do |previous_employment|
            = render 'previous_employment_fields', f: previous_employment
          .links
            = link_to_add_association 'Add Job', f, :previous_employments, class: 'btn btn-success btn-sm'
      %fieldset
        %legend
          Skills
        .form-group
          = f.input :skills, label: 'Please list any Job Skills you have:', wrapper_html: { class: 'col-sm-12' }
      %fieldset
        %legend
          Work Visa
        .form-group
          = f.input :work_visa, as: :radio_buttons, label: "Do you have a work visa?", collection: [['Yes', true], ['No', false]], checked: true, item_wrapper_class: 'radio-inline', wrapper_html: { id: 'work-visa', class: 'col-sm-12' }
          = f.input :visa_country, label: 'Work Visa Country', collection: ['Hong Kong', 'Macau', 'China'], input_html: { class: 'work-visa-hide' }, wrapper_html: { class: 'col-sm-6'}
          = f.input :visa_exp_date, label: 'Visa Expiration Date', start_year: Date.today.year, end_year: Date.today.year + 40, include_blank: true, item_wrapper_class: 'form-inline', input_html: { class: 'work-visa-hide'}, wrapper_html: { class: 'col-sm-12'}
      %fieldset
        %legend
          Passport  
        .form-group  
          = f.input :passport_country, label: 'Passport Country', as: :country, priority: Cv::PREFERRED_COUNTRIES
          = f.input :passport_expiration_date, label: 'Expiration Date', start_year: Date.today.year, end_year: Date.today.year + 40
      %fieldset
        %legend
          Photos
        .form-group
          %strong.col-xs-12 You will need 2 pictures of yourself.
          %br
          %strong.col-xs-12 1 needs to be a clear photo of your face.
          %br
          %strong.col-xs-12 1 needs to be a full-body photo.
          %br
          %br
          .col-sm-6
            .panel.panel-primary
              .panel-heading
                Face Photo
              .panel-body
                = f.input :head_pic, as: :file, label: false
          .col-sm-6
            .panel.panel-primary
              .panel-heading
                Body Photo
              .panel-body
                = f.input :body_pic, as: :file, label: false
  
    .form-actions
      = f.button :submit, 'Save My CV', class: 'btn-success btn-lg'

:javascript 
  $('input[type=radio]').on("change", function() {
    if ($(this).val() == "true") {
      $('.work-visa-hide').prop('disabled', false);
    } else {
      $('.work-visa-hide').prop('disabled', true);
    }
  });
  $("input[value='English']").prop('readonly', true);
  $("input[value='Cantonese']").prop('readonly', true);
  $("input[value='Mandarin']").prop('readonly', true);

app/views/cvs/_language_fields.html.haml
.form-group.nested-fields.clearfix
  = f.input :name, wrapper_html: { class: 'col-sm-4' }
  = f.input :read, collection: @language_levels, wrapper_html: { class: 'col-xs-6 col-sm-2' }
  = f.input :write, collection: @language_levels, wrapper_html: { class: 'col-xs-6 col-sm-2' }
  = f.input :speak, collection: @language_levels, wrapper_html: { class: 'col-xs-6 col-sm-2' }
  = f.input :listen, collection: @language_levels, wrapper_html: { class: 'col-xs-6 col-sm-2' }
  - unless f.object.name == 'English' || f.object.name == 'Mandarin' || f.object.name == 'Cantonese'
    .links.clearfix
      = link_to_remove_association "Remove Language", f, class: 'btn btn-danger btn-sm pull-right'
%hr

app/views/cvs/_previous_employment_fields.html.haml
.nested-fields
  .form-group
    = f.input :employer_name, label: 'Employer', wrapper_html: { class: 'col-sm-6' }
    = f.input :location, wrapper_html: { class: 'col-sm-6' }
  .form-group
    %strong.col-sm-3 How long did you work there:
    = f.input :years, label: 'Years', collection: 0..40, input_html: { style: 'width: 80px' }, wrapper_html: { class: 'col-sm-2' }
    = f.input :months, label: 'Months', collection: 0..12, input_html: { style: 'width: 80px' }, wrapper_html: { class: 'col-sm-2' }
    = f.input :ended_year, label: 'Year Finished', collection: 1900..2100, wrapper_html: { class: 'col-sm-4' }
  .form-group
    = f.input :job_duties, label: 'Explain what you did for this job', wrapper_html: { class: 'col-sm-12' }
  .links.clearfix
    = link_to_remove_association "Remove Job", f, class: 'btn btn-danger btn-sm pull-right'
  %hr

app/views/cvs/edit.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.text-center
        %h3 Please Complete the CV Form
      .panel-body
        = render 'form'

app/views/cvs/index.html.haml
%h1 Listing cvs

%table
  %thead
    %tr
      %th User
      %th First name
      %th Middle name
      %th Last name
      %th Age
      %th Height
      %th Weight
      %th Marital status
      %th Children
      %th Phone number
      %th Current address l1
      %th Current address l2
      %th Current city
      %th Current country
      %th Skills
      %th Work visa
      %th Visa exp date
      %th Nationality
      %th
      %th
      %th

  %tbody
    - @cvs.each do |cv|
      %tr
        %td= cv.user
        %td= cv.first_name
        %td= cv.middle_name
        %td= cv.last_name
        %td= cv.age
        %td= cv.height
        %td= cv.weight
        %td= cv.marital_status
        %td= cv.children
        %td= cv.phone_number
        %td= cv.current_address_L1
        %td= cv.current_address_L2
        %td= cv.current_city
        %td= cv.current_country
        %td= cv.skills
        %td= cv.work_visa
        %td= cv.visa_exp_date
        %td= cv.nationality
        %td= link_to 'Show', cv
        %td= link_to 'Edit', edit_cv_path(cv)
        %td= link_to 'Destroy', cv, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Cv', new_cv_path

app/views/cvs/new.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading.text-center
        %h3 Please Complete the CV Form
      .panel-body
        = render 'form'

app/views/cvs/show.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .panel.panel-primary
      .panel-heading
        %h3
          Profile for
          = current_user.username
      .panel-body
        %p#notice= notice
        .row
          .col-sm-2
            %b UserName:
          .col-sm-2
            = current_user.username
          .col-sm-2.col-sm-offset-3
            %b Email:
          .col-sm-2
            = current_user.email
        %br
        .row
          .col-sm-2
            %b Name:
          .col-sm-3
            = current_user.cv.first_name + " " + current_user.cv.middle_name + " " + current_user.cv.last_name
          .col-sm-2.col-sm-offset-2
            %b Age:
          .col-sm-2
            = current_user.cv.age
        %br
        .row
          .col-sm-2
            %b Height:
          .col-sm-2
            = current_user.cv.height
          .col-sm-2.col-sm-offset-3
            %b Weight:
          .col-sm-2
            = current_user.cv.weight
        %br
        .row
          .col-sm-2
            %b Marital Status:
          .col-sm-2
            = current_user.cv.marital_status
          .col-sm-2.col-sm-offset-3
            %b Children:
          .col-sm-2
            = current_user.cv.children
        %br
        .row
          .col-sm-2
            %b Address:
          .col-sm-3
            #{current_user.cv.current_address}
            %br
            #{current_user.cv.current_city}, #{current_user.cv.current_country}
          .col-sm-2.col-sm-offset-2
            %b Phone Number:
          .col-sm-2
            = current_user.cv.phone_number
        %br
        .row
          .col-sm-2
            %b Nationality:
          .col-sm-2
            = current_user.cv.passport_country
          .col-sm-2
            %b Passport Number:
          .col-sm-2
            = current_user.cv.passport_number
          .col-sm-2
            %b Passport Exp Date:
          .col-sm-2
            = current_user.cv.passport_expiration_date
        %br
        .row
          .col-sm-2
            %b Has Work Visa?:
          .col-sm-2
            - if current_user.cv.work_visa
              Yes
            - else
              No
          .col-sm-2
            %b Visa Exp Date:
          .col-sm-2
            = current_user.cv.visa_exp_date
        %br
        .row
          .col-sm-2
            %b Skills
          .col-sm-6
            = current_user.cv.skills
        %br
        .row
          .col-sm-2
            %b Languages:
          .col-sm-2
            %b Read
          .col-sm-2
            %b Write
          .col-sm-2
            %b Speak
          .col-sm-2
            %b Listen
        - current_user.cv.languages.each do |l|
          .row
            .col-sm-2
              = l.name
            .col-sm-2
              = l.read
            .col-sm-2
              = l.write
            .col-sm-2
              = l.speak
            .col-sm-2
              = l.listen
        - if !current_user.cv.previous_employments.nil?
          %br
          .row
            .col-sm-2
              %b Job Name:
            .col-sm-2
              %b How Long
            .col-sm-2
              %b Last Year
            .col-sm-6
              %b Job Description
          - current_user.cv.previous_employments.each do |j|
            .row
              .col-sm-2
                = j.employer_name
              .col-sm-2
                #{j.years} Years, #{j.months} Months
              .col-sm-2
                = j.ended_year
              .col-sm-6
                = j.job_duties
        .row
          .col-sm-6
            .panel.panel-primary
              = image_tag current_user.cv.head_pic.url(:thumb)
          .col-sm-6
            .panel.panel-primary
              = image_tag current_user.cv.body_pic.url(:thumb)
        
        