config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users, only: [:index, :show]
  resources :users do
    resources :cvs
  end
  resources :agents
  resources :jobs

  match '/about', to: 'static_pages#about', via: :get
  match '/faq', to: 'static_pages#faq', via: :get

  root to: "jobs#index"

  post 'user_jobs/add'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Macau-Jobs
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    %nav.navbar.navbar-toggleable-md.navbar-default.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{ type: :button, 'data-toggle' => :collapse, 'data-target' => "#topNav" }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Macau-Jobs.com", root_path, class: "navbar-brand"
        .collapse.navbar-collapse#topNav
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              - if current_user.admin
                %li
                  = link_to "New Job Post", new_job_path
                %li
                  = link_to "Workers", users_path
                %li
                  = link_to "Agents", agents_path
              - else
                %li
                  = link_to "Your Account", edit_user_registration_path
                %li
                  - if current_user.cv.nil? || current_user.cv.id.nil?
                    = link_to "Your CV", new_user_cv_path(current_user, @cv)
                  - else
                    = link_to "Your CV", edit_user_cv_path(current_user, current_user.cv)
              %li
                = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign In", new_user_session_path
              %li
                = link_to "Sign Up", new_user_registration_path

    .container.content
      = yield